(() => {
'use strict';
const modules=[
 {title:'Placas, Cores e Caminhos',description:'Entenda os sinais que vão guiar você.',topic:'Sinalização'},
 {title:'Escolhas e Consequências',description:'Conheça as regras e o peso de cada decisão.',topic:'Legislação'},
 {title:'Na Direção da Segurança',description:'Antecipe riscos e pratique escolhas seguras.',topic:'Direção defensiva'},
 {title:'Cuidar, Agir e Preservar',description:'Cuide de você, do veículo e do nosso mundo.',topic:'Cuidados e prevenção'}
];
const app=document.getElementById('app');
let session=null,interval=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
const fmt=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
function header(){return `<header class="top"><button class="brand" data-action="home" aria-label="Voltar ao início"><span class="brand-symbol" aria-hidden="true">♡</span><span class="brand-name">Para Pâmela, <small>com amor Marcos,</small></span></button><span class="topnote">Sua próxima conquista começa aqui ♡</span></header>`;}
function footer(){return `<footer class="footer"><span>Feito com carinho, para acompanhar cada conquista sua. <span class="heart">♥</span></span><span>Material de estudo independente · Não é uma prova oficial do DETRAN.</span></footer>`;}
function focusHeading(){const h=app.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
function home(){clearInterval(interval);session=null;app.innerHTML=`<div class="shell">${header()}<main><div class="intro"><div><div class="eyebrow">Um passo de cada vez, meu amor</div><h1>Meu Amor, a próxima conquista é sua.</h1><p class="muted">Escolha um módulo e vamos juntas rumo à sua CNH.</p></div><div class="love-note">“Eu acredito em você.<br>E vou torcer por você em cada caminho.” <span aria-hidden="true">♡</span></div></div><div class="layout"><section aria-labelledby="modules-title"><div class="section-label"><h2 id="modules-title">Seu cantinho de estudos</h2><span>4 módulos do curso</span></div><div class="modules">${modules.map((m,i)=>`<article class="module"><div class="module-top"><span class="module-num">0${i+1}</span><span class="small muted">${m.topic}</span></div><h3>${m.title}</h3><p>${m.description}</p><div class="meta"><span>15 questões</span><span>◷ 15 minutos</span></div><div class="module-actions"><button class="btn secondary" data-action="start" data-mode="${i+1}">Estudar módulo <span aria-hidden="true">↗</span></button><a class="pdf" href="assets/modulo-${i+1}.pdf" target="_blank" rel="noopener">Ler PDF</a></div></article>`).join('')}</div></section><aside><section class="final-card"><div class="eyebrow">Todos os caminhos se encontram</div><h2>Seu simulado<br>geral.</h2><p>Uma prova com os quatro módulos para colocar seu aprendizado em prática.</p><div class="final-stats"><div><strong>30</strong><small>questões</small></div><div><strong>60</strong><small>minutos</small></div></div><button class="btn" data-action="start" data-mode="final">Começar simulado <span aria-hidden="true">→</span></button></section><div class="aside-note"><p><strong>Errar também faz parte de aprender.</strong></p><p>No final, veja suas respostas, entenda cada erro e encontre a página do curso para revisar.</p><p>O tempo começa ao iniciar e a prova é entregue automaticamente quando ele acabar.</p></div></aside></div><details><summary>Sobre as questões e o material de apoio</summary><p>60 questões nos módulos e 30 questões próprias no simulado geral, elaboradas a partir dos quatro PDFs enviados. As placas são imagens extraídas do curso. Perguntas e alternativas mudam de ordem a cada tentativa.</p><p>Os tempos de 15 e 60 minutos são deste treino. O resultado indica seu desempenho, sem equivaler à aprovação no exame oficial. Ao atualizar ou fechar a página, a tentativa em andamento é perdida.</p><p>Referências complementares: <a href="https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm" target="_blank" rel="noopener">Código de Trânsito Brasileiro</a> e <a href="https://www.gov.br/saude/pt-br/composicao/saes/samu-192" target="_blank" rel="noopener">SAMU — Ministério da Saúde</a>.</p></details></main>${footer()}</div>`;}
function start(mode){clearInterval(interval);const isFinal=mode==='final';const source=isFinal?window.QUESTION_BANK.final:window.QUESTION_BANK.modules.filter(q=>q.module===Number(mode));const questions=shuffle(source).map(q=>{const order=shuffle(q.options.map((text,i)=>({text,correct:i===q.correct})));return {...q,options:order.map(o=>o.text),correct:order.findIndex(o=>o.correct)};});const seconds=isFinal?3600:900;session={mode,questions,answers:Array(questions.length).fill(null),index:0,started:Date.now(),deadline:Date.now()+seconds*1000,duration:seconds,finished:false};renderQuestion();interval=setInterval(tick,250);focusHeading();}
function sign(q){if(!q.image)return '';const compact=!['servicos','destinos','turismo'].includes(q.image);return `<figure class="sign-box"><img class="${compact?'compact':''}" src="assets/${q.image}.png" alt="${imageAlt[q.image]||'Placa de trânsito apresentada na questão'}" width="${compact?180:400}" height="${compact?180:220}"></figure>`;}
const imageAlt={pare:'Placa vermelha octogonal com a palavra PARE',preferencia:'Placa triangular invertida, branca com borda vermelha',estacionar:'Placa circular com letra E cortada por uma faixa diagonal vermelha',parar:'Placa circular com letra E cortada por duas faixas vermelhas em X',sentido:'Placa circular com seta para cima cortada por faixa vermelha',velocidade:'Placa circular com borda vermelha e número 80 km/h',curva:'Placa amarela em losango com seta em ângulo para a direita',lombada:'Placa amarela com elevação arredondada no centro da base',escola:'Placa amarela com figuras de escolares sobre marcas de travessia',obras:'Placa alaranjada com pessoa usando uma ferramenta no solo',escorregadia:'Placa amarela com carro e marcas sinuosas atrás dos pneus',servicos:'Placa azul com símbolos de abastecimento, oficina, alimentação e estacionamento, a 500 metros',destinos:'Placa verde: Vassouras 5 km, Paraíba do Sul 57 km, Três Rios 64 km',turismo:'Placa marrom com setas, símbolos e nomes: Véu de Noiva, Mirante, Parque Cidade e Lagoa Azul'};
function title(){return session.mode==='final'?'Simulado geral':modules[Number(session.mode)-1].title;}
function renderQuestion(){if(!session||session.finished)return;const {questions,answers,index}=session,q=questions[index],count=answers.filter(x=>x!==null).length;app.innerHTML=`<div class="shell">${header()}<main><div class="exam-head"><div><div class="eyebrow">${session.mode==='final'?'Os quatro módulos':`Módulo 0${session.mode}`}</div><h1>${title()}</h1><span class="small muted">Respira, meu amor. Uma questão de cada vez.</span></div><div class="timer" id="timer" role="timer" aria-label="Tempo restante"><span>Tempo restante</span><strong id="clock"></strong></div></div><div class="exam-layout"><section class="question-card" aria-labelledby="question-title"><div class="question-top"><span>Questão ${index+1} de ${questions.length}</span><span>${modules[q.module-1].topic}</span></div><progress max="${questions.length}" value="${count}" aria-label="Questões respondidas"></progress>${sign(q)}<h2 id="question-title">${escape(q.question)}</h2><fieldset class="choices"><legend class="sr-only">Escolha uma alternativa</legend>${q.options.map((o,i)=>`<label class="choice"><input type="radio" name="answer" value="${i}" ${answers[index]===i?'checked':''}><span class="choice-letter">${'ABCD'[i]}</span><span>${escape(o)}</span></label>`).join('')}</fieldset><div class="question-nav"><button class="btn secondary" data-action="prev" ${index===0?'disabled':''}>← Anterior</button>${index<questions.length-1?'<button class="btn" data-action="next">Próxima →</button>':'<button class="btn" data-action="finish">Finalizar →</button>'}</div></section><aside class="navigator"><h3>Suas questões</h3><div class="number-grid">${questions.map((_,i)=>`<button class="${answers[i]!==null?'answered ':''}${i===index?'current':''}" data-action="jump" data-index="${i}" aria-label="Questão ${i+1}${answers[i]!==null?', respondida':', em branco'}" ${i===index?'aria-current="step"':''}>${i+1}</button>`).join('')}</div><div class="legend"><span id="answered-count">${count}</span> de ${questions.length} respondidas.<br>Rosa: respondida · Borda: atual</div><p class="small muted">Você pode voltar e alterar qualquer resposta antes de finalizar.</p><button class="btn" data-action="finish">Finalizar simulado</button><button class="text-btn" data-action="home">Sair do simulado</button></aside></div><div id="time-alert" class="sr-only" role="status"></div></main>${footer()}</div>`;tick();}
function tick(){if(!session||session.finished)return;const remaining=Math.max(0,Math.ceil((session.deadline-Date.now())/1000));const clock=document.getElementById('clock');if(clock)clock.textContent=fmt(remaining);document.getElementById('timer')?.classList.toggle('urgent',remaining<=60);if(remaining<=60&&!session.warned){session.warned=true;const alert=document.getElementById('time-alert');if(alert)alert.textContent='Falta um minuto. A prova será entregue automaticamente ao terminar o tempo.';}if(remaining<=0)finish(true);}
function ask(kind){if(!session||session.finished){home();return;}tick();if(session.finished)return;const blanks=session.answers.filter(x=>x===null).length;const finishing=kind==='finish';const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>${finishing?'Pronta para conferir?':'Sair desta tentativa?'}</h2><p>${finishing?blanks?`Ainda há ${blanks} ${blanks===1?'questão em branco':'questões em branco'}. Elas serão contabilizadas como não respondidas, sem acerto.`:'Todas as questões estão respondidas. Ao entregar, você poderá ver o resultado e as explicações.':'As respostas desta tentativa serão perdidas. Você pode continuar e terminar com calma.'}</p><p class="small muted">O cronômetro continua enquanto esta janela está aberta.</p><div class="actions"><button class="btn secondary" data-cancel>Continuar</button><button class="btn" data-confirm>${finishing?'Entregar agora':'Sair'}</button></div>`;document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-confirm]').onclick=()=>{dialog.close();if(finishing)finish(false);else home();};dialog.showModal();}
function finish(timedOut){if(!session||session.finished)return;session.finished=true;session.timedOut=timedOut||Date.now()>=session.deadline;session.elapsed=Math.min(session.duration,Math.max(0,Math.floor((Date.now()-session.started)/1000)));clearInterval(interval);document.querySelectorAll('dialog').forEach(d=>d.close());renderResults();focusHeading();}
function review(q,i){const a=session.answers[i],correct=a===q.correct;return `<article class="review ${correct?'correct':'wrong'}"><span class="tag">Questão ${i+1} · ${a===null?'Não respondida':correct?'Acertou':'Vamos revisar'}</span><h3>${escape(q.question)}</h3>${sign(q)}${!correct?`<div class="answer missed"><strong>Sua resposta:</strong> ${a===null?'Você deixou esta questão em branco.':escape(q.options[a])}</div>`:''}<div class="answer right"><strong>Resposta correta:</strong> ${escape(q.options[q.correct])}</div><div class="explanation"><p><strong>Por quê?</strong> ${escape(q.explanation)}</p><a class="small" href="assets/modulo-${q.module}.pdf#page=${q.page}" target="_blank" rel="noopener">Revisar no PDF: módulo ${q.module}, página ${q.page} ↗</a></div></article>`;}
function renderResults(){const {questions,answers}=session;const correct=questions.filter((q,i)=>answers[i]===q.correct).length,blank=answers.filter(a=>a===null).length,wrong=questions.length-correct-blank;const needsReview=questions.map((q,i)=>({q,i})).filter(({q,i})=>answers[i]!==q.correct);const right=questions.map((q,i)=>({q,i})).filter(({q,i})=>answers[i]===q.correct);app.innerHTML=`<div class="shell">${header()}<main><div class="result-top"><div class="eyebrow">${title()} · ${session.timedOut?'Tempo encerrado':'Tentativa concluída'}</div><h1>${correct===questions.length?'Você acertou todas, meu amor!':'Mais um passo na sua conquista. ♡'}</h1><p class="muted">${session.timedOut?'A entrega foi automática ao terminar o tempo. ':''}${needsReview.length?'Cada revisão é uma chance de aprender. Vamos entender o que ficou pelo caminho?':'Seu estudo está dando frutos. Continue praticando com carinho e atenção.'}</p></div><div class="score-summary"><div><strong>${correct}/${questions.length}</strong><small>acertos</small></div><div><strong>${Math.round(correct/questions.length*100)}%</strong><small>de aproveitamento</small></div><div><strong>${wrong}</strong><small>erradas</small></div><div><strong>${blank}</strong><small>em branco</small></div><div><strong>${fmt(session.elapsed)}</strong><small>tempo utilizado</small></div></div><div class="result-actions"><button class="btn" data-action="retry">Tentar novamente</button><button class="btn secondary" data-action="home">Escolher outro módulo</button></div><h2>Aprender com cada resposta</h2>${needsReview.length?`<p class="muted">${needsReview.length} ${needsReview.length===1?'questão para revisar':'questões para revisar'}, incluindo as que ficaram em branco.</p>${needsReview.map(({q,i})=>review(q,i)).join('')}`:'<p>Nenhuma questão errada ou em branco nesta tentativa. Muito bem! ♥</p>'}${right.length?`<details><summary>Ver também as ${right.length} questões corretas e suas explicações</summary>${right.map(({q,i})=>review(q,i)).join('')}</details>`:''}</main>${footer()}</div>`;}
app.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;if(action==='start'){start(button.dataset.mode);return;}if(action==='home'){if(session&&!session.finished)ask('exit');else{home();focusHeading();}return;}if(action==='retry'){start(session.mode);return;}if(!session||session.finished)return;tick();if(session.finished)return;if(action==='finish')ask('finish');else if(['next','prev','jump'].includes(action)){session.index=action==='jump'?Number(button.dataset.index):session.index+(action==='next'?1:-1);renderQuestion();const h=document.getElementById('question-title');h.tabIndex=-1;h.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}});
app.addEventListener('change',event=>{if(!event.target.matches('input[name="answer"]')||!session||session.finished)return;tick();if(session.finished)return;session.answers[session.index]=Number(event.target.value);const count=session.answers.filter(x=>x!==null).length;document.getElementById('answered-count').textContent=count;app.querySelector('progress').value=count;const current=app.querySelector('.number-grid .current');current.classList.add('answered');current.setAttribute('aria-label',`Questão ${session.index+1}, respondida`);});
window.addEventListener('beforeunload',event=>{if(session&&!session.finished){event.preventDefault();event.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
home();
})();
